baseURL="https://comnamu18.github.io"
languageCode = "ko-kr"
title = "computer_namu"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "KimSangHeon"
  description = "Computer + Namu"
  github = "comnamu18"
  linkedin = "comnamu18-shkim"
  url="https://comnamu18.github.io"
  email = "comnamu18@gmail.com"
  keywords = "DL, ML, Prototyping"
  lastmod = true
  favicon = "/images/github.png"
  location = "Seoul, Republic of Korea"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]