languageCode = "ko-kr"
title = "computer_namu"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "comnamu18"
  description = "Want to make ML/DL projects commercially"
  github = "comnamu18"
  linkedin = "comnamu18-shkim"
  email = "comnamu18@gmail.com"
  keywords = "DL, ML, Prototyping"
  lastmod = true
  favicon = "/images/github.png"
  location = "Seoul, Republic of Korea"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]